name: UI Playwright TS

on:
  push:
    paths:
      - 'ui-playwright-ts/**'
      - '.github/workflows/ui-playwright.yml'
  pull_request:
    paths:
      - 'ui-playwright-ts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-playwright-ts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui-playwright-ts/playwright-report
